on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  build_and_pipelinescan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file app/pom.xml
    - name: Veracode Pipeline
      run: |
        curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
        unzip -o pipeline-scan-LATEST.zip
        java -jar pipeline-scan.jar --veracode_api_id "${{secrets.VID}}" --veracode_api_key "${{secrets.VKEY}}" --file "verademo.war" --issue_details true || true
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/results.json
        name: VeracodeBaseline
        
  veracode_sca_agent_based:
    needs: build_and_pipelinescan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Veracode_SCA_Agent_Based
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SCA }}
        run: |
          curl -sSL 'https://download.sourceclear.com/ci.sh' | bash -s – scan --update-advisor --allow-dirty
                    
